[package]
name = "spur-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "spur"
path = "src/main.rs"

[dependencies]
spur-proto = { path = "../spur-proto" }
spur-client = { path = "../spur-client" }
spur-core = { path = "../spur-core" }
spur-update = { path = "../spur-update" }
spur-net = { path = "../spur-net" }
clap = { workspace = true }
tonic = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing-subscriber = { workspace = true }
prost-types = { workspace = true }
tokio-stream = "0.1"
whoami = "2.1.1"
nix = { workspace = true, features = ["user"] }
libc = "0.2"
crossterm = "0.29"
tar = { workspace = true }
flate2 = { workspace = true }
reqwest = { workspace = true }
shlex = "2"
rcgen = { version = "0.14.10", default-features = false, features = ["pem", "aws_lc_rs"] }

[dev-dependencies]
flate2 = { workspace = true }
serial_test = { workspace = true }
tempfile = "3"
x509-parser = "0.18.1"
zstd = { workspace = true }

[lints]
workspace = true
